/**
 * CSV template generation.
 *
 * These functions produce the exact bytes that the upload parsers expect.
 * Every design decision here is driven by parser compatibility:
 *
 *   - Column names match the canonical keys in HEADER_MAP / GRADE_HEADER_MAP
 *     exactly, so normaliseHeader() maps them without any alias lookup.
 *
 *   - Sample rows use values that pass every Zod rule in the validators,
 *     so users can upload the unmodified template as a smoke-test.
 *
 *   - Comment rows begin with "#" — the upload routes strip them before
 *     passing text to parseStudentCSV / parseGradeCSV, so users do NOT
 *     need to delete them. We keep them for human readability.
 *
 *   - UTF-8 BOM (\uFEFF) is prepended so Excel on Windows opens the file
 *     with correct character encoding without any manual import steps.
 *     The parsers already strip the BOM on receipt.
 *
 *   - CRLF (\r\n) line endings because Excel on Windows writes CRLF and
 *     many institutional IT environments reject LF-only CSV files.
 *     The parsers handle both endings.
 *
 *   - Fields that contain commas are quoted. Fields that contain quotes
 *     have the quote doubled. No field in these templates currently needs
 *     quoting, but the helper is applied uniformly for safety.
 *
 * Nothing in this file imports from DB or Next.js — safe to call from
 * API routes, server actions, and unit tests.
 */

import { DEFAULT_GRADE_SCALE } from "@/lib/gpa/scale";

// ─── Shared CSV utilities ─────────────────────────────────────────────────────

const CRLF = "\r\n";
const BOM = "\uFEFF";

/** Quote a CSV field if it contains commas, double-quotes, or newlines. */
function csvField(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

/** Join an array of fields into one CSV row string (no line ending). */
function csvRow(fields: string[]): string {
  return fields.map(csvField).join(",");
}

/** Join lines with CRLF and prepend UTF-8 BOM. */
function buildCSV(lines: string[]): string {
  return BOM + lines.join(CRLF) + CRLF;
}

// ─── Shared comment block builder ─────────────────────────────────────────────

function commentBlock(lines: string[]): string[] {
  return lines.map((l) => (l === "" ? "#" : `# ${l}`));
}

// ─── Student template ─────────────────────────────────────────────────────────

/**
 * Column order mirrors the canonical HEADER_MAP in lib/bulk/parser.ts.
 * Changing this order does NOT break the parser (it maps by name, not position)
 * but keeping it stable prevents confusion for users who re-download the template.
 */
const STUDENT_HEADERS = [
  "indexNumber",
  "firstName",
  "lastName",
  "programmeCode",
  "level",
  "entryYear",
  "graduationYear",
] as const;

type StudentSampleRow = {
  indexNumber: string;
  firstName: string;
  lastName: string;
  programmeCode: string;
  level: string;
  entryYear: string;
  graduationYear: string;
};

/**
 * Three sample rows:
 *   Row 1 — active Level 100 student, no graduation year
 *   Row 2 — active Level 200 student, no graduation year
 *   Row 3 — graduated student with graduation year filled
 *
 * All three pass the Zod schema in lib/bulk/validator.ts exactly as written.
 * The programmeCode "BSC-CS" is a placeholder — users must replace it with a
 * code that exists in their system (shown on the upload page).
 */
const STUDENT_SAMPLE_ROWS: StudentSampleRow[] = [
  {
    indexNumber: "CS/2024/001",
    firstName: "Ama",
    lastName: "Mensah",
    programmeCode: "BSC-CS",
    level: "100",
    entryYear: "2024",
    graduationYear: "",
  },
  {
    indexNumber: "CS/2023/045",
    firstName: "Kofi",
    lastName: "Asante",
    programmeCode: "BSC-CS",
    level: "200",
    entryYear: "2023",
    graduationYear: "",
  },
  {
    indexNumber: "ENG/2020/012",
    firstName: "Abena",
    lastName: "Owusu",
    programmeCode: "BSC-ENG",
    level: "400",
    entryYear: "2020",
    graduationYear: "2024",
  },
];

const STUDENT_COMMENTS = commentBlock([
  "STUDENT BULK UPLOAD TEMPLATE",
  "Generated by the Transcript Management System",
  "",
  "INSTRUCTIONS:",
  "  1. Replace the sample rows below with your student data.",
  "  2. Do NOT modify the header row (row after these comments).",
  "  3. Comment rows (starting with #) are stripped automatically on upload.",
  "  4. programmeCode must exactly match an active programme in the system.",
  "  5. level must be one of: 100, 200, 300, 400, 500, 600, 700, 800",
  "  6. entryYear must be a 4-digit year, e.g. 2024",
  "  7. graduationYear is optional — leave the cell blank for current students.",
  "  8. indexNumber must be unique across all students in the system.",
  "",
  "COLUMN REFERENCE:",
  "  indexNumber    | Required | Unique student ID, e.g. CS/2024/001",
  "  firstName      | Required | Student's given name",
  "  lastName       | Required | Student's family/surname",
  "  programmeCode  | Required | Must match an existing active programme code",
  "  level          | Required | Academic level: 100, 200, 300, 400, 500, 600, 700, 800",
  "  entryYear      | Required | 4-digit year of first admission, e.g. 2024",
  "  graduationYear | Optional | 4-digit graduation year — blank for current students",
]);

export function generateStudentTemplate(): string {
  const lines = [
    ...STUDENT_COMMENTS,
    csvRow([...STUDENT_HEADERS]),
    ...STUDENT_SAMPLE_ROWS.map((r) =>
      csvRow([
        r.indexNumber,
        r.firstName,
        r.lastName,
        r.programmeCode,
        r.level,
        r.entryYear,
        r.graduationYear,
      ]),
    ),
  ];

  return buildCSV(lines);
}

// ─── Grades template ──────────────────────────────────────────────────────────

/**
 * Column order mirrors the canonical GRADE_HEADER_MAP in lib/bulk/grades/parser.ts.
 */
const GRADE_HEADERS = [
  "indexNumber",
  "courseCode",
  "semester",
  "year",
  "grade",
] as const;

const VALID_GRADE_LETTERS = Object.keys(DEFAULT_GRADE_SCALE).join(", ");

type GradeSampleRow = {
  indexNumber: string;
  courseCode: string;
  semester: "FIRST" | "SECOND";
  year: string;
  grade: string;
};

/**
 * Six sample rows across two students and two semesters.
 * Every grade letter appears at least once across the three grade-column values.
 * semester is the canonical "FIRST" / "SECOND" form — the normaliser also
 * accepts "1", "2", "first", "second" etc., but templates should model best practice.
 */
const GRADE_SAMPLE_ROWS: GradeSampleRow[] = [
  {
    indexNumber: "CS/2024/001",
    courseCode: "MATH101",
    semester: "FIRST",
    year: "2024",
    grade: "A",
  },
  {
    indexNumber: "CS/2024/001",
    courseCode: "PHYS101",
    semester: "FIRST",
    year: "2024",
    grade: "B+",
  },
  {
    indexNumber: "CS/2024/001",
    courseCode: "COMP101",
    semester: "SECOND",
    year: "2024",
    grade: "B",
  },
  {
    indexNumber: "CS/2023/045",
    courseCode: "MATH101",
    semester: "FIRST",
    year: "2024",
    grade: "C+",
  },
  {
    indexNumber: "CS/2023/045",
    courseCode: "PHYS101",
    semester: "FIRST",
    year: "2024",
    grade: "C",
  },
  {
    indexNumber: "CS/2023/045",
    courseCode: "COMP101",
    semester: "SECOND",
    year: "2024",
    grade: "F",
  },
];

const GRADE_COMMENTS = commentBlock([
  "GRADE BULK UPLOAD TEMPLATE",
  "Generated by the Transcript Management System",
  "",
  "INSTRUCTIONS:",
  "  1. Replace the sample rows below with your results data.",
  "  2. Do NOT modify the header row (row after these comments).",
  "  3. Comment rows (starting with #) are stripped automatically on upload.",
  "  4. indexNumber must match an existing student in the system.",
  "  5. courseCode must match an existing active course in the system.",
  "  6. semester must be FIRST or SECOND (case-insensitive; also accepts 1 or 2).",
  "  7. year is the academic year start, e.g. 2024 for the 2024/2025 session.",
  "     The semester (year + FIRST/SECOND) must already exist in the system.",
  `  8. grade must be one of: ${VALID_GRADE_LETTERS}`,
  "",
  "COMPUTED AUTOMATICALLY — DO NOT ADD THESE COLUMNS:",
  "  gradePoint, creditHours, computedQualityPoints",
  "  These are computed server-side from the grade and course record.",
  "  Any columns with these names will be ignored.",
  "",
  "COLUMN REFERENCE:",
  "  indexNumber | Required | Must match an existing student's index number",
  "  courseCode  | Required | Must match an existing active course code",
  "  semester    | Required | FIRST or SECOND",
  "  year        | Required | 4-digit academic year start, e.g. 2024",
  `  grade       | Required | ${VALID_GRADE_LETTERS}`,
]);

export function generateGradesTemplate(): string {
  const lines = [
    ...GRADE_COMMENTS,
    csvRow([...GRADE_HEADERS]),
    ...GRADE_SAMPLE_ROWS.map((r) =>
      csvRow([r.indexNumber, r.courseCode, r.semester, r.year, r.grade]),
    ),
  ];

  return buildCSV(lines);
}

// ─── Metadata (used by the UI) ────────────────────────────────────────────────

export type TemplateSpec = {
  id: "students" | "grades";
  label: string;
  description: string;
  filename: string;
  endpoint: string;
  columns: readonly string[];
  sampleCount: number;
};

export const TEMPLATE_SPECS = [
  {
    id: "students",
    label: "Student upload template",
    description: "Import multiple students at once. One student per row.",
    filename: "student-upload-template.csv",
    endpoint: "/api/templates/students",
    columns: STUDENT_HEADERS,
    sampleCount: STUDENT_SAMPLE_ROWS.length,
  },
  {
    id: "grades",
    label: "Grade upload template",
    description:
      "Import results for multiple students. One course result per row.",
    filename: "grade-upload-template.csv",
    endpoint: "/api/templates/grades",
    columns: GRADE_HEADERS,
    sampleCount: GRADE_SAMPLE_ROWS.length,
  },
] as const satisfies TemplateSpec[];
